global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: ['keycloak:8080']

  - job_name: krakend
    static_configs:
    - targets: ['krakend:8091']

  - job_name: client
    static_configs:
      - targets: ['pyclient:5000']

